# -*- coding: utf-8 -*-
"""레거시 호환 표면의 명시적 export 계약 (레거시 축소 단계 1→5).

이 목록은 회귀·계약 시험과 CLI가 실제로 쓰는 이름 전수를 고정한다.
- kind: alias(다른 모듈 재수출) · adapter(legacy 정의) · 경로 · 상수·상태 ·
  모듈 참조 · legacy-class(호환 서브클래스)
- owner: 배정 당시 소유 모듈. 미사용이 되어도 한 릴리스 동안 지우지 않는다.
이 파일과 test_legacy_exports_contract.py가 표면 드리프트를 차단한다.

## 축소 완료 후 legacy_surface 잔여 구획 색인 (2026-07-30, 4,208줄 실측)

각 구획이 남아 있는 호환 이유:

- 재수출 import 81건(340줄): 과거 단일 파일 시절 이름을 같은 자리에서
  제공한다 — 회귀 299개 monkeypatch 지점과 alias 44개의 근거.
- 경로·부트스트랩·상수 132할당(280줄): PROGRAM_DIR·BASE_DIR·프로필·
  DEFAULT_CONFIG·OPTIONS·pace 기본값 등. 사용자 자료 위치의 진실이며
  시험이 patch.object(APP, "BASE_DIR", …)로 직접 바꾼다.
- 셔틀 함수 170개(≤4줄): 서비스·wiring 호출을 legacy 이름으로 노출한다.
  이것이 계획서의 "필요한 최소 adapter"다 — 줄 압축 금지 원칙에 따라
  한 이름당 한 함수를 유지한다.
- 실질 adapter ~200개(호출 인자 조립·예외 문구 유지):
  call_nai_api(조각 해석 주입)·save_config(`_` 키 필터)·out_root 등.
- 클래스 3개(30줄): ConfigServer(namespace 고정 서브클래스)·LiveState·
  PublicCollectionManager 어댑터 — 계획서가 alias 유지를 명시.
- Operations/Paths 조립: **0건** (runtime/wiring/ 5모듈 + web/
  application_server로 전부 이동).

### 이동 후보 8함수 — 서비스로 이동 완료 (이름은 위임으로 유지)

setting_reference_config·character_resource_config → character_runtime,
save_scenes(정규화부) → settings_handlers.normalize_scene_rows,
activate_comparison_run·_comparison_result_context → comparison_runtime,
_nai_json_metadata → metadata_audit, ensure_schema_split·setting_thumbs
→ setting_store. 경계 상한 4,000이 역증가를 막는다.
"""
from __future__ import annotations

LEGACY_EXPORTS = {
    "APIError": {"kind": "alias", "owner": "src.nai_studio.services.nai_client"},
    "BACKUP_SCHEMA": {"kind": "상수·상태", "owner": "compat.legacy_surface"},
    "BASE_DIR": {"kind": "경로", "owner": "compat.legacy_surface(부트스트랩)"},
    "BLUEPRINT_GENERATION_KEYS": {"kind": "상수·상태", "owner": "compat.legacy_surface"},
    "BUILDER_FILE": {"kind": "경로", "owner": "compat.legacy_surface(부트스트랩)"},
    "CHAR_DIR": {"kind": "경로", "owner": "compat.legacy_surface(부트스트랩)"},
    "COMBO_FILE": {"kind": "경로", "owner": "compat.legacy_surface(부트스트랩)"},
    "COMPARE_MODE_LABELS": {"kind": "상수·상태", "owner": "compat.legacy_surface"},
    "COMPARE_PROGRESS_FILE": {"kind": "경로", "owner": "compat.legacy_surface(부트스트랩)"},
    "CONFIG_FILE": {"kind": "경로", "owner": "compat.legacy_surface(부트스트랩)"},
    "ConfigServer": {"kind": "legacy-class", "owner": "src.nai_studio.compat.legacy_surface"},
    "DATAPACK_SCHEMA": {"kind": "상수·상태", "owner": "compat.legacy_surface"},
    "DATA_INDEX_SCHEMA": {"kind": "상수·상태", "owner": "compat.legacy_surface"},
    "DEFAULT_CONFIG": {"kind": "상수·상태", "owner": "compat.legacy_surface"},
    "FRAG_DIR": {"kind": "경로", "owner": "compat.legacy_surface(부트스트랩)"},
    "IMG_CACHE": {"kind": "경로", "owner": "compat.legacy_surface(부트스트랩)"},
    "JOB_LEDGER_FILE": {"kind": "경로", "owner": "compat.legacy_surface(부트스트랩)"},
    "LIBRARY_REVIEW_FILE": {"kind": "경로", "owner": "compat.legacy_surface(부트스트랩)"},
    "LOG_FILE": {"kind": "경로", "owner": "compat.legacy_surface(부트스트랩)"},
    "LegacyPromotionLineageUnavailable": {"kind": "alias", "owner": "src.nai_studio.services.comparison_promotion"},
    "LiveState": {"kind": "legacy-class", "owner": "src.nai_studio.compat.legacy_surface"},
    "MAX_CHARS": {"kind": "상수·상태", "owner": "compat.legacy_surface"},
    "OPTIONS_FILE": {"kind": "경로", "owner": "compat.legacy_surface(부트스트랩)"},
    "PAGE_TEMPLATE": {"kind": "상수·상태", "owner": "compat.legacy_surface"},
    "PICKS_FILE": {"kind": "경로", "owner": "compat.legacy_surface(부트스트랩)"},
    "PREVIEW_PORT_RANGE": {"kind": "상수·상태", "owner": "compat.legacy_surface"},
    "PROFILE_DIR": {"kind": "경로", "owner": "compat.legacy_surface(부트스트랩)"},
    "PublicCollectionManager": {"kind": "legacy-class", "owner": "src.nai_studio.compat.legacy_surface"},
    "QUALITY_SUFFIX": {"kind": "상수·상태", "owner": "compat.legacy_surface"},
    "QUALITY_SUFFIX_TEXT": {"kind": "상수·상태", "owner": "compat.legacy_surface"},
    "RATINGS_FILE": {"kind": "경로", "owner": "compat.legacy_surface(부트스트랩)"},
    "RateLimitError": {"kind": "alias", "owner": "src.nai_studio.services.nai_client"},
    "SCENESET_DIR": {"kind": "경로", "owner": "compat.legacy_surface(부트스트랩)"},
    "SCENES_FILE": {"kind": "경로", "owner": "compat.legacy_surface(부트스트랩)"},
    "SCHEMA_DIR": {"kind": "경로", "owner": "compat.legacy_surface(부트스트랩)"},
    "SETTINGS_DIR": {"kind": "경로", "owner": "compat.legacy_surface(부트스트랩)"},
    "SETTINGS_FILE": {"kind": "경로", "owner": "compat.legacy_surface(부트스트랩)"},
    "SPEC_FILE": {"kind": "경로", "owner": "compat.legacy_surface(부트스트랩)"},
    "STARTUP_RECOVERY_NOTICE": {"kind": "상수·상태", "owner": "compat.legacy_surface"},
    "STYLE_DIR": {"kind": "경로", "owner": "compat.legacy_surface(부트스트랩)"},
    "STYLE_FILE": {"kind": "경로", "owner": "compat.legacy_surface(부트스트랩)"},
    "TAG_DIR": {"kind": "경로", "owner": "compat.legacy_surface(부트스트랩)"},
    "TRASH_DIR_NAME": {"kind": "상수·상태", "owner": "compat.legacy_surface"},
    "VIBE_DIR": {"kind": "경로", "owner": "compat.legacy_surface(부트스트랩)"},
    "_COMBOS": {"kind": "상수·상태", "owner": "compat.legacy_surface"},
    "_LAST_CALL": {"kind": "상수·상태", "owner": "compat.legacy_surface"},
    "_RATINGS": {"kind": "상수·상태", "owner": "compat.legacy_surface"},
    "_TAGV_CACHE": {"kind": "상수·상태", "owner": "compat.legacy_surface"},
    "_ac_cache_load": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "_ac_cache_save": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "_ac_index": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "_ac_index_inner": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "_backup_merge_secrets": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "_build_std": {"kind": "alias", "owner": "src.nai_studio.services.setting_compiler"},
    "_build_yuri": {"kind": "alias", "owner": "src.nai_studio.services.setting_compiler"},
    "_comparison_character_prompt": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "_comparison_progress_load": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "_finish_durable_job": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "_load_styles_raw": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "_local_import_image": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "_migrate_legacy": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "_nai_json_metadata": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "_prompt_parts": {"kind": "alias", "owner": "src.nai_studio.domain.image_metadata"},
    "_ref_fields": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "_rerun_selected_comparison": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "_result_promotion_records": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "_run_comparison": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "_run_generation": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "_style_record_from_public_image": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "_tags_json": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "_tags_json_at": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "_validate_datapack_manifest": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "_variety_sigma_value": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "_write_styles_raw": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "activate_comparison_run": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "active_people": {"kind": "alias", "owner": "src.nai_studio.services.character_runtime"},
    "add_style": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "anlas_estimate": {"kind": "alias", "owner": "src.nai_studio.domain.costs"},
    "annotate_nai_comment": {"kind": "alias", "owner": "src.nai_studio.domain.nai_payload"},
    "apply_evaluation_action": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "arca_public": {"kind": "모듈 참조", "owner": "src.nai_studio.collection.arca"},
    "artist_workspace_request": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "atomic_write_json": {"kind": "alias", "owner": "src.nai_studio.runtime.data_files"},
    "autocomplete_tags": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "base64": {"kind": "모듈 참조", "owner": "base64"},
    "blueprint_common": {"kind": "alias", "owner": "src.nai_studio.domain.project_inheritance"},
    "call_director": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "call_nai_api": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "character_resource_config": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "close_application_logging": {"kind": "alias", "owner": "src.nai_studio.runtime.logging_config"},
    "common_job_store": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "comparison_character_setting_job_values": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "comparison_character_setting_plan": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "comparison_characters": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "comparison_job_recipe_snapshot": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "comparison_job_values": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "comparison_plan": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "comparison_progress_summary": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "comparison_recipe_for_output": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "comparison_runs": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "comparison_selected_job_values": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "comparison_selected_plan": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "comparison_settings": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "comparison_signature": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "comparison_sources": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "comparison_style_config": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "comparison_styles": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "compose_artist_workspace": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "compute_pending": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "date": {"kind": "alias", "owner": "datetime"},
    "datetime": {"kind": "alias", "owner": "datetime"},
    "derive_setting_catalog": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "diagnostic_event_line": {"kind": "alias", "owner": "src.nai_studio.runtime.diagnostics"},
    "duplicate_setting_scene": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "ensure_settings_migration": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "export_legacy_resources": {"kind": "alias", "owner": "src.nai_studio.services.resource_bridge"},
    "export_user_backup": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "extract_nai_metadata": {"kind": "alias", "owner": "src.nai_studio.domain.image_metadata"},
    "fetch_anlas_balance": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "fetch_cached_image": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "finalized_token_texts": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "fingerprint_blueprint": {"kind": "alias", "owner": "src.nai_studio.domain.blueprint"},
    "finish_job_record": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "fixed_seed": {"kind": "alias", "owner": "src.nai_studio.domain.nai_payload"},
    "folder_inventory_page": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "from_legacy_job_record": {"kind": "alias", "owner": "src.nai_studio.runtime.jobs"},
    "generation_blueprint": {"kind": "alias", "owner": "src.nai_studio.services.generation_blueprint"},
    "generation_context_fingerprint": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "generation_task_fingerprint": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "import_char_files": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "import_datapack_bytes": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "inherited_blueprint_resolution": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "iter_character_setting_jobs": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "iter_comparison_jobs": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "iter_selected_comparison_jobs": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "job_ledger_summary": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "link_job_ancestor": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "list_fragments": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "list_output": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "list_settings": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "list_styles": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "list_trash_batches": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "load_asset_config": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "load_builder": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "load_combos": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "load_job_ledger": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "load_json_recover": {"kind": "alias", "owner": "src.nai_studio.runtime.data_files"},
    "load_options": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "load_or_init_config": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "load_pack_log": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "load_picks": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "load_ratings": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "load_recipes": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "load_settings_recover": {"kind": "alias", "owner": "src.nai_studio.runtime.data_files"},
    "load_spec": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "load_state": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "local_image_integrity": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "local_overrides": {"kind": "alias", "owner": "src.nai_studio.domain.project_inheritance"},
    "log": {"kind": "기타", "owner": "logging.Logger"},
    "main": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "make_progress_record": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "merge_quality_suffix": {"kind": "alias", "owner": "src.nai_studio.domain.model_presets"},
    "merge_uc_preset": {"kind": "alias", "owner": "src.nai_studio.domain.model_presets"},
    "metadata_audit_adapter": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "metadata_audit_candidate": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "metadata_audit_save_candidate": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "migrate_legacy_program_data": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "migrate_legacy_selections": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "model_id_from_metadata": {"kind": "alias", "owner": "src.nai_studio.domain.model_presets"},
    "nai_tokens": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "new_job": {"kind": "alias", "owner": "src.nai_studio.runtime.jobs"},
    "new_setting": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "normalize_comparison_options": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "normalize_local_image_refs": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "organize_library_items": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "out_sub": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "output_file_for_preview": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "pace_complete": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "pace_gate": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "pack_log_brief": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "parse_diagnostic_lines": {"kind": "alias", "owner": "src.nai_studio.runtime.diagnostics"},
    "prepare_char_refs": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "prepare_vibes": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "preview_datapack_bytes": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "preview_user_backup": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "progress_record_path": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "progress_record_valid": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "promote_comparison_recipe_assets": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "quality_suffix_text": {"kind": "alias", "owner": "src.nai_studio.domain.model_presets"},
    "random": {"kind": "모듈 참조", "owner": "random"},
    "rate_artist": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "rebuild_data_index": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "record_job_result": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "recover_job_ledger": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "recoverable_remove": {"kind": "alias", "owner": "src.nai_studio.runtime.data_files"},
    "reference_inset_canvas": {"kind": "alias", "owner": "src.nai_studio.services.character_bench"},
    "render_page": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "requests": {"kind": "모듈 참조", "owner": "requests"},
    "resolve_data_dir": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "resolve_fragments": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "resource_file_index": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "restore_quality_prompt": {"kind": "alias", "owner": "src.nai_studio.domain.model_presets"},
    "restore_styles": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "restore_trash_batch": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "restore_user_backup": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "retry_after_seconds": {"kind": "alias", "owner": "src.nai_studio.services.nai_client"},
    "rollback_local_image_normalize": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "rollback_user_backup": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "runtime_generation_params": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "save_config": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "save_pack_log": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "save_picks": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "save_state": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "save_style_file": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "save_with_meta": {"kind": "alias", "owner": "src.nai_studio.services.result_store"},
    "scene_mode_pending": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "search_combos": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "search_library": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "setting_add_set": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "setting_cast_members": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "setting_content_revision": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "setting_delete": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "setting_meta_save": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "setting_reference_config": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "setting_scene_people": {"kind": "alias", "owner": "src.nai_studio.services.setting_compiler"},
    "setting_state": {"kind": "alias", "owner": "src.nai_studio.services.setting_compiler"},
    "setting_thumbs": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "slot_prompt": {"kind": "alias", "owner": "src.nai_studio.services.character_runtime"},
    "split_quality_suffix": {"kind": "alias", "owner": "src.nai_studio.domain.model_presets"},
    "split_uc_preset": {"kind": "alias", "owner": "src.nai_studio.domain.model_presets"},
    "spread_centers": {"kind": "alias", "owner": "src.nai_studio.domain.positioning"},
    "strip_metadata": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "style_bundle_signature": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "style_rating": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "sync_chars_to_files": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "threading": {"kind": "모듈 참조", "owner": "threading"},
    "time": {"kind": "모듈 참조", "owner": "time"},
    "transition_job": {"kind": "alias", "owner": "src.nai_studio.runtime.jobs"},
    "trash_output_files": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "uc_preset_text": {"kind": "alias", "owner": "src.nai_studio.domain.model_presets"},
    "undo_datapack": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "undo_duplicate_setting_scene": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "uuid": {"kind": "모듈 참조", "owner": "uuid"},
    "validate_config_value": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "variety_sigma": {"kind": "alias", "owner": "src.nai_studio.domain.nai_payload"},
    "verify_tags": {"kind": "adapter", "owner": "src.nai_studio.compat.legacy_surface"},
    "webbrowser": {"kind": "모듈 참조", "owner": "webbrowser"},
}

# 이동 전 기준선 — endpoint 문자열은 web/routes 밖으로 나오지 않는다.
ROUTE_BASELINE = (
    "/api/ac",
    "/api/anlas",
    "/api/archive_download_control",
    "/api/artist_workspace",
    "/api/backup_export",
    "/api/backup_preview",
    "/api/backup_restore",
    "/api/backup_rollback",
    "/api/blueprint",
    "/api/blueprint_project",
    "/api/booru",
    "/api/character_variation_save",
    "/api/combos",
    "/api/compare_activate",
    "/api/compare_catalog",
    "/api/compare_preview",
    "/api/compare_progress",
    "/api/compare_promote",
    "/api/compare_recipe",
    "/api/compare_rerun",
    "/api/compare_run",
    "/api/compare_runs",
    "/api/config",
    "/api/data_index_rebuild",
    "/api/data_storage",
    "/api/diag",
    "/api/director",
    "/api/evaluation_action",
    "/api/folder_inventory",
    "/api/frag_del",
    "/api/frag_export",
    "/api/frag_import",
    "/api/frag_reset",
    "/api/frag_save",
    "/api/frag_try",
    "/api/generate_one",
    "/api/i2i",
    "/api/img_origins",
    "/api/inspect",
    "/api/job_command",
    "/api/jobs",
    "/api/library",
    "/api/library_organize",
    "/api/local_image_integrity",
    "/api/local_image_normalize",
    "/api/local_image_rollback",
    "/api/merge_apply",
    "/api/merge_preview",
    "/api/merge_undo",
    "/api/metadata_audit_candidate",
    "/api/metadata_audit_control",
    "/api/metadata_audit_save",
    "/api/metadata_audit_status",
    "/api/mosaic_save",
    "/api/norm_save",
    "/api/option_item",
    "/api/out_list",
    "/api/pack_import",
    "/api/pack_log",
    "/api/pack_preview",
    "/api/pack_preview_cancel",
    "/api/pack_undo",
    "/api/picks_del",
    "/api/picks_restore",
    "/api/picks_save",
    "/api/public_collection",
    "/api/public_collection_control",
    "/api/public_collection_pairing",
    "/api/public_collection_relay",
    "/api/public_collection_restoration",
    "/api/public_collection_retry",
    "/api/public_collection_start",
    "/api/rate",
    "/api/recipes",
    "/api/ref_add",
    "/api/ref_bundle_export",
    "/api/ref_bundle_import",
    "/api/ref_save",
    "/api/regen",
    "/api/restoration_batch",
    "/api/role_save",
    "/api/save",
    "/api/sb_addset",
    "/api/sb_del",
    "/api/sb_meta",
    "/api/sb_new",
    "/api/sb_renumber",
    "/api/scene_duplicate",
    "/api/scene_duplicate_undo",
    "/api/scene_preview",
    "/api/scene_save",
    "/api/scenes",
    "/api/scenes_run",
    "/api/scenes_save",
    "/api/sceneset_save",
    "/api/setting_dup",
    "/api/setting_export",
    "/api/setting_import",
    "/api/setting_sequence",
    "/api/setting_thumbs",
    "/api/start",
    "/api/stop",
    "/api/strip_meta",
    "/api/style_del",
    "/api/style_dupes",
    "/api/style_restore",
    "/api/style_save",
    "/api/tags",
    "/api/tokens",
    "/api/trash",
    "/api/update_download",
    "/api/update_install",
    "/api/update_status",
    "/api/verify_tags",
    "/img",
    "/latest.webp",
    "/refimg",
    "/setout",
    "/status.json",
)

__all__ = ["LEGACY_EXPORTS", "ROUTE_BASELINE"]
